helooo ayabe 
aisv;emgb,w

,
sb'rwb
rw,b'mwtbw
'mwtbw'mwtbw
ryane is heerere


we all all thhe things that i do
and we all d waht we thinkhat we need
we aisv
aisvas

aisvase
rerwgrw
tgrwtb'rw,
'w w,b   wb we